name: Release Raw Module

on:
    push:
        tags:
            - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies for cross-compiling
        run: |
          sudo apt update 
          sudo apt-get --no-install-recommends --yes install \
            upx libc6-dev-amd64-cross \
            gcc-aarch64-linux-gnu libc6-dev-arm64-cross \
            gcc-arm-linux-gnueabihf libc6-dev-armhf-cross 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # setup node
      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/pnpm-lock.yaml
          node-version: lts/iron
          cache: 'pnpm'

      # install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          pnpm install
      
      - name: Build app
        working-directory: ./frontend
        run: |
          pnpm build

      - name: Generate code
        run: |
          go generate
      
      - name: Build Backend
        run: |
          go build -o ./raw/usr/bin/zimaos-terminal ./main.go
      
      - name: Move Frontend
        run: |
          mv ./frontend/dist ./raw/usr/share/casaos/www/modules/zimaos_terminal
      - run: |
          mksquashfs raw/ zimaos_terminal.raw

      - name: '更新 Update release'
        uses: zhanghengxin/git-release-private@ice
        with:
            token: ${{ secrets.CICD_GITHUB_TOKEN }}
            allow_override: true
            gzip: false
            prerelease: true
            tag: ${{ steps.get_version.outputs.VERSION }}
            files: ./zimaos_terminal.raw